### ISSUE TITLE
Replace the wysiwyg module by the ckeditor module

### ISSUE THREAD

**Issue by Luukyb** [promet/drupal7-framework#10]
We should be using the ckeditor module by default instead of the wysiwyg module.
ckeditor will be in core for Drupal-8 based on the ckeditor module, already availble for Drupal 7.
See "Drupal 7 - Future-proof your Drupal 7 site" https://www.drupal.org/node/2287495

**Comment by dsdobrzynski** [comment]
WYSIWYG module has now been replaced by the CKEditor module and the default configuration updated.
